export const copyCatalog = Object.freeze({
  brand: {
    productName: "오즈코딩스쿨 인블로그 자동화",
    version: "v1.0a",
    chatVersion: "v1.0a",
    pageTitle: "OZ 디부캠 인블로그 UI"
  },
  navigation: {
    saved: "저장됨",
    disconnected: "Codex 연결 끊김",
    connected: "Codex 연결됨",
    guide: "가이드",
    list: "목록",
    profile: "프로필",
    close: "닫기"
  },
  workflow: {
    rail: "워크플로우 진행 상황",
    stateSummary: "상태 요약",
    factCheck: "검토 필요 (Fact-check)",
    debugJson: "Debug JSON 보기",
    loading: "생각 중",
    sessionListLoading: "세션 목록을 불러오는 중…",
    fixtureTitle: "JSON 샘플 테스트",
    fixtureDescription: "보존된 v0.3 fixture를 읽기 위한 렌더링 테스트",
    fixtureShortDescription: "보존된 v0.3 fixture 렌더링",
    open: "열기",
    readOnly: "열람",
    resume: "이어쓰기",
    sessionListEmpty: "디스크에서 읽을 수 있는 과거 세션이 없습니다.",
    sessionListError: "세션 목록을 불러오지 못했습니다",
    sessionLoadError: "대화를 불러오지 못했습니다",
    unknownError: "알 수 없는 오류",
    stop: "중단"
  },
  newArticle: {
    title: "새 글 시작",
    subject: "대상",
    seedKind: "자료 유형",
    seedUrls: "시작 자료 URL",
    initialInterest: "관심 지점",
    comparisonHints: "비교 힌트",
    editorNotes: "에디터 메모",
    researchDepth: "조사 깊이",
    targetSourceCount: "목표 자료 수",
    seedKindArticle: "기사·리포트",
    seedKindOfficial: "공식 자료",
    seedKindPaper: "논문·연구",
    seedKindOther: "기타",
    depthLight: "가볍게",
    depthStandard: "표준",
    depthDeep: "깊게",
    start: "조사 범위 저장",
    loading: "조사 범위를 저장하고 있습니다",
    success: "조사 범위를 저장했습니다.",
    retry: "다시 시도",
    requiredSubject: "대상을 입력해 주세요.",
    invalidUrl: "시작 자료 URL 형식을 확인해 주세요.",
    invalidCount: "목표 자료 수를 확인해 주세요."
  },
  sourceSelection: {
    searchPlaceholder: "검색어를 입력하세요",
    searchLabel: "자료 검색",
    detail: "자세히 보기",
    openDetail: "상세 내용 열기",
    select: "선택",
    clearSearch: "검색어 지우기",
    reset: "초기화",
    empty: "검색 결과가 없습니다",
    loading: "자료를 찾고 있습니다",
    retry: "Research 다시 시도",
    selected: "선택한 자료"
  },
  writing: {
    edit: "편집",
    copy: "복사",
    copied: "복사됨",
    exportMarkdown: "MD 내보내기",
    apply: "수정본 적용",
    eyebrow: "Writing",
    title: "본문 편집",
    close: "닫기",
    sentenceConcise: "문장 간결화",
    paragraphFlow: "문단 정리",
    brunchTone: "브런치 톤",
    introStrengthen: "도입 강화",
    conclusionStrengthen: "결론 강화",
    sentenceConcisePrompt: "문장을 조금 더 간결하게 다듬어 주세요.",
    paragraphFlowPrompt: "문단 사이의 흐름이 자연스럽게 이어지도록 정리해 주세요.",
    brunchTonePrompt: "브런치에 어울리게 조금 더 자연스럽고 사람 말투처럼 다듬어 주세요.",
    introStrengthenPrompt: "도입부의 몰입감을 더 높여 주세요.",
    conclusionStrengthenPrompt: "마지막 문단에 여운이 남도록 다듬어 주세요.",
    toneDefault: "기본",
    toneShort: "짧게",
    toneProvocative: "더 도발적",
    toneLabel: "원고 스타일",
    versionOptionsLabel: "답변 버전",
    requestPlaceholder: "Ask for Changes",
    thinkingPlaceholder: "Thinking...",
    askAi: "AI에게 요청",
    humanizer: "Humanizer",
    refining: "원고를 다듬는 중",
    saving: "저장 중",
    saved: "저장됨",
    retrySave: "수정본 저장 다시 시도",
    saveFailed: "저장하지 못했습니다. 수정 내용을 확인한 뒤 다시 시도해 주세요."
  },
  brunchChat: {
    welcome: "## oz-inblog에 오신 것을 환영합니다\n\n오늘은 어떤 글을 써볼까요?\n글감을 찾고, 선택한 주제를 조사하고, 목차와 원고까지 한 단계씩 이어갑니다.\n\n### 이렇게 시작할 수 있어요\n\n- **새 글감 찾기**\n\n  최근 디자인·브랜딩·제품 이슈에서 쓸 만한 사건을 찾아봅니다.\n\n- **생각해둔 주제 조사하기**\n\n  이미 떠올린 주제의 사실과 사례를 확인합니다.\n\n- **작성한 초안 점검하기**\n\n  초안의 흐름과 주장, 문장을 함께 살펴봅니다.\n\n\n**선택지에서 시작점을 고르거나, 원하는 작업을 직접 입력하세요.**",
    choiceTitle: "어떤 방향으로 진행하시겠어요?",
    userResponse: "User Response",
    userInput: "User Input",
    inputPlaceholder: "메시지를 입력하세요",
    chatboxPlaceholder: "메시지를 입력하거나, 명령을 입력하세요",
    stepInputPlaceholder: "아니요, 다르게 해야 할 내용을 설명해 주세요",
    continue: "계속 ↵",
    copy: "복사",
    copyResponse: "응답 복사",
    copyPreview: "원고 복사",
    copied: "복사됨",
    regenerate: "다시 생성",
    versionHistory: "이전 답변",
    branch: "여기서 이어가기",
    currentVersion: "현재 답변",
    modelSelect: "모델 선택",
    newChat: "새 대화",
    sessionListEyebrow: "Brunch Chat",
    sessionListDescription: "저장된 Brunch 대화를 불러오거나 새 대화를 시작합니다.",
    loading: "생각 중",
    thinking: "생각 중",
    generationActivity: {
      request_received: "요청을 확인하고 있어요",
      archive_reading: "이전 브런치 글을 살펴보고 있어요",
      topic_searching: "최신 주제를 찾고 있어요",
      candidate_editing: "글감 후보를 정리하고 있어요",
      topic_source_searching: "선택한 주제의 자료를 찾고 있어요",
      evidence_synthesizing: "근거와 사례를 확인하고 있어요",
      direction_editing: "글의 방향을 다듬고 있어요",
      outline_editing: "제목과 전체 구성을 정리하고 있어요",
      article_writing: "전체 원고를 작성하고 있어요",
      local_editing: "요청한 부분을 수정하고 있어요",
      structural_editing: "글의 구조와 흐름을 다듬고 있어요",
      full_rewriting: "원고를 다시 작성하고 있어요",
      claim_verifying: "수치와 근거를 확인하고 있어요",
      writing_skill_running: "원고의 문체를 다듬고 있어요",
      readiness_evaluating: "원고의 발행 준비도를 확인하고 있어요",
      finishing_response: "확인한 내용으로 답변을 마무리하고 있어요",
      saving: "수정한 원고를 저장하고 있어요",
      interrupted: "작업을 중단했어요",
      failed: "작업을 완료하지 못했어요"
    },
    topicRetry: "모두 별로예요. 다시 찾아주세요",
    error: "응답을 받지 못했습니다. 잠시 후 다시 시도해 주세요.",
    networkError: "채팅 서버에 연결하지 못했습니다. 서버가 실행 중인지 확인한 뒤 다시 시도해 주세요.",
    timeout: "응답이 길어져 끝까지 마무리하지 못했습니다. 지금까지 확인한 근거로 다시 정리해 주세요.",
    emptyMessage: "메시지를 입력하거나 선택지를 골라 주세요.",
    stop: "중단",
    writingPreview: "Writing Preview",
    welcomeQuestion: "오늘 어떤 글을 함께 써볼까요?",
    storageRestoreError: "저장된 대화를 복원하지 못했습니다. 새 대화로 시작해 주세요.",
    sessionListEmpty: "저장된 Brunch 대화가 없습니다.",
    readiness: {
      pending: "확인 전",
      evaluating: "원고를 검토하고 있어요",
      needsWork: "보완 필요",
      almostReady: "거의 준비됨",
      ready: "발행 준비됨",
      stale: "수정되어 다시 확인이 필요해요",
      failed: "완성도를 확인하지 못했어요",
      retry: "다시 확인",
      detailStatusCaption: "발행 준비도",
      detailReasonCaption: "판단 사유",
      detailDimensionsCaption: "세부 기준",
      detailBlockersCaption: "수정 제안",
      summaryFallback: "원고의 구조와 근거를 다시 확인해 주세요.",
      blocker: "수정 제안",
      dimensions: "세부 검토",
      score: "점",
      lastChecked: "마지막 확인",
      dimensionLabels: {
        central_judgment: "중심 판단",
        title_contract: "제목과 본문",
        structure_conclusion: "구조와 결론",
        evidence_boundaries: "근거 경계",
        voice_readability: "문체와 가독성"
      }
    }
  }
});

export function catalogValues(value) {
  if (typeof value === "string") return [value];
  if (!value || typeof value !== "object") return [];
  return Object.values(value).flatMap(catalogValues);
}

export const visibleCopy = Object.freeze(catalogValues(copyCatalog));
